import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/darkmode/theme-provider";
import { Footer } from "@/components/Footer";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from 'next-intl/server';


const vazir = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const isRTL = locale === 'fa';

  return (
    <div lang={locale} dir={isRTL ? 'rtl' : 'ltr'} >
      <div
        className={` ${vazir.variable} antialiased font-vazir min-h-screen flex flex-col`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="flex-1 pt-20">
              {children}
            </div>
            <Footer/>
          </ThemeProvider>
        </NextIntlClientProvider>
      </div>
    </div>
  );
}
